development:
  sessions:
    default:
      database: hk_coders_camp_2012_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: hk_coders_camp_2012_test
      hosts:
        - localhost:27017
        
production:
  uri: <%= ENV['MONGOLAB_URI'] %>