development:
  sessions:
    default:
      database: hk_coders_camp_2012_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: hk_coders_camp_2012_test
      hosts:
        - localhost:27017
        
production:
  sessions:
    default:  
      hosts: 
        - <%= ENV['MONGOLAB_HOST'] %>
      database: <%= ENV['MONGOLAB_DATABASE'] %>
      username: <%= ENV['MONGOLAB_USER'] %>
      password: <%= ENV['MONGOLAB_PASSWORD'] %>